services:
  wrlc_fastapi_webhook:
    build: .
    container_name: wrlc_fastapi_webhook
    volumes:
      - .:/app
    working_dir: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wrlc_fastapi_webhook.rule=Host(`webhook.wrlc.localhost`)"
      - "traefik.http.routers.wrlc_fastapi_webhook.tls=true"
      - "traefik.http.routers.wrlc_fastapi_webhook.entrypoints=websecure"
    environment:
      SMTP_SERVER: "localhost"
      SMTP_PORT: "8025"
      SMTP_SSL: "False"
    secrets:
      - ssh_key
      - gitconfig
    networks:
      - proxy

secrets:
  ssh_key:
    file: ${SSH_KEY_FILE}
  gitconfig:
    file: ${GITCONFIG}
volumes:
    mysql-data:

networks:
  proxy:
    external: true
