[tool.poetry]
name = "wrlc-fastapi-webhook"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.115.7"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
